### ISSUE TITLE
InternalOAuthError: Failed to fetch user profile

### ISSUE THREAD

**Issue by irokhes** [drudge/passport-facebook-token#38]
Hi,

I'm getting this error when I tried to get the user profile from facebook

```javascript
InternalOAuthError: Failed to fetch user profile
at /Users/jorgereyero/Workspace/xxxxx/node_modules/passport-facebook-token/lib/index.js:147:32
    at passBackControl (/Users/jorgereyero/Workspace/xxxxx/node_modules/passport-facebook-token/node_modules/passport-oauth/node_modules/passport-oauth2/node_modules/oauth/lib/oauth2.js:123:9)
    at IncomingMessage.<anonymous> (/Users/jorgereyero/Workspace/xxxxx/node_modules/passport-facebook-token/node_modules/passport-oauth/node_modules/passport-oauth2/node_modules/oauth/lib/oauth2.js:143:7)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickDomainCallback (node.js:381:11)

```

Thanks,

Jorge.

**Comment by ghaiklor** [comment]
@irokhes send your code and how I can reproduce it

**Comment by irokhes** [comment]
Hi,

this is the way I'm using it:

route.js

```javascript
var usercontroller = require('../bin/www/controllers/users/usercontroller.js');
var passport = require('passport');
var routes = function(app) {
    /**
     * Init webservice route.
     * @method InitWebSerivceRoutes
     * */
    function InitWebServiceRoutes(app) {
    
        app.route('/api/user/loginFb').post(passport.authenticate('facebook-token'), usercontroller.loginFb);

    }
    InitWebServiceRoutes(app);

    //other unregistered url will be redirected to 404 page, this line should always be the last line
   }
```

app.js

```javascript
/**
 * Module dependencies.
 */
var express = require('express');
var path = require('path');
var logger = require('morgan');
var cookieParser = require('cookie-parser');
var bodyParser = require('body-parser');
var config = require('./config/appconfig.js');
var expressValidator = require('express-validator');
var passport = require('passport');
FacebookTokenStrategy = require('passport-facebook-token');

var http = require('http');
var authfactory = require('./bin/www/factories/auth/authfactory.js');
var app = express();
// Configuration
app.use(logger('dev'));
app.set('views', __dirname + '/views');
app.set('view engine', 'ejs');
app.disable('etag');
app.use(bodyParser.json());
app.use(expressValidator());
app.use(bodyParser.urlencoded({
    extended: true
}));
app.use(passport.initialize());
app.use(express.static(__dirname + '/public'));

passport.serializeUser(function(user, done) {
  done(null, user);
});

passport.deserializeUser(function(user, done) {
  done(null, user);
});


passport.use(new FacebookTokenStrategy({
    clientID: 'clientID',
    clientSecret: 'clientSecret'
  },
  function(accessToken, refreshToken, profile, done) {
      console.dir(profile);
      return done(null, {username: profile.emails[0].value, id:profile.id, name:profile.name});
  }
));

```

I was working before (after you updated the library) but no idea what is happening 

Thanks

**Comment by ghaiklor** [comment]
@irokhes did you try provide custom function in `authenticate()` method?
Try and log what happens there.

**Comment by irokhes** [comment]
No, the code I've sent in the previous comment is all I'm using.

**Comment by ghaiklor** [comment]
@irokhes as I said, try to use custom method in `authenticate()` method.

```javascript
app.route('/api/user/loginFb').post(passport.authenticate('facebook-token', function() {
  console.log(arguments);
}));
```

Another variant is expired token from your side.

**Comment by irokhes** [comment]
@ghaiklor I've changed my code trying to log the response from facebook but the execution doesn't go that far, it throws and exception in the library (the one I posted before)

the new code looks like you suggested 

```javascript
app.route('/api/user/loginFb').post(passport.authenticate('facebook-token'), 
            function (req, res) {
            // do something with req.user
            console.log('@@@@@@@@');
            console.log(req);
  }         );
```

**Comment by ghaiklor** [comment]
@irokhes can you check your token ? I'm wondering why your code isn't working. We are using this library in our projects and when I published this release we check it.

Also, you can hack module in node_modules and try to log what happens in `userProfile` method in `this.oauth2.get()` callback.

**Comment by irokhes** [comment]
Hi @ghaiklor there must be something wrong with the tokens I was using because it works with different ones. Thanks for you help.
