### ISSUE TITLE
"Error: Failed to serialize user into session" even when not using passport.session() middleware

### ISSUE THREAD

**Issue by ismail-khan** [drudge/passport-facebook-token#63]
I am using passport-facebook-token to authenticate users who use a RESTful API.  At the moment I want to authenticate users every time they make an API call, and so I did not add the passport.session() middleware.

**However**, every time I try to authenticate I get the following error:

`Error: Failed to serialize user into session`

When I add the following code, everything starts working as normal:

```
passport.serializeUser((user, done) => done(null, user));
passport.deserializeUser((user, done) => done(null, user));
```

Why is this happening even though I am specifically NOT using the passport.session() middleware? Why do I need to call serializeUser & deserializeUser when there is no session recorded?

Here is all the code to reproduce the error:

```
"use strict"; // Enables ES6 features

// Import modules
const express = require('express');
const path = require('path');
const bodyParser = require('body-parser');
const passport = require('passport');
const FacebookTokenStrategy = require('passport-facebook-token');

// Constants
const PORT = process.env.PORT || 8080;

// Create app and add middleware
const app = express();
app.use(bodyParser.json());
app.use(passport.initialize());
// app.use(passport.session()); Should I use session??

// Implement (de)serializeUser methods -- Do I need this?
// passport.serializeUser((user, done) => done(null, user));
// passport.deserializeUser((user, done) => done(null, user));

/*
 * Set up passport strategy
 */
passport.use('facebook-token', new FacebookTokenStrategy(
    {
    clientID        : process.env.FACEBOOK_APP_ID,
    clientSecret    : process.env.FACEBOOK_SECRET
  },
  (accessToken, refreshToken, profile, done) => {

    const user = {
        'firstName' : profile.name.givenName,
      'lastName'    : profile.name.familyName,
      'id'              : profile.id,
    }

    // Perform actions against User model here

    return done(null, user); // the user object we just made gets passed to the route's controller as `req.user`
  }
));

/*
 * User is logging in
 */
app.post(
    "/login",
    passport.authenticate('facebook-token'),
    (err, req, res) => {

        if (req.user) {
            res.json(req.user); // Return user object
        }
        else {
            res.status(400).json({"error": "Failed to authenticate user"}); // This is never called!
        }
    }
);

/*
 * Initialize app
 */
const server = app.listen(PORT, () => {
    const port = server.address().port;
    console.log("App now running on port", port);
});


```

**Comment by Joshuabaker2** [comment]
Did you ever figure out your solution? Running into the same issue

**Comment by Arcrammer** [comment]
@Joshuabaker2 It's still complaining for me. Think you could take a quick look at my code?

Here's the route:
```javascript
router.post('/iOS/signup', function (req, res, next) {
  passport.authenticate('local', {session: false}, function (err, user, info) {
    if (err) {
      res.json({
        "success": false,
        "error": err
      });
    }

    if (!user) {
      res.json({
        "success": false,
        "user": null
      });
    }

    req.logIn(user, function (err) {
      if (err) {
        return next(err);
      }

      res.json({
        "success": true,
        "user": user
      });
    });
  })(req, res, next);
});
```

When I send a request to `http://10.0.0.8:3000/auth/iOS/signup` it shows me this in Terminal:
```bash
Error: Failed to serialize user into session
    at pass (/Users/alexander/Sites/TCP-Express/node_modules/passport/lib/authenticator.js:277:19)
    at serialized (/Users/alexander/Sites/TCP-Express/node_modules/passport/lib/authenticator.js:282:7)
    at /Users/alexander/Sites/TCP-Express/passport.js:19:2
    at pass (/Users/alexander/Sites/TCP-Express/node_modules/passport/lib/authenticator.js:290:9)
    at Authenticator.serializeUser (/Users/alexander/Sites/TCP-Express/node_modules/passport/lib/authenticator.js:295:5)
    at IncomingMessage.req.login.req.logIn (/Users/alexander/Sites/TCP-Express/node_modules/passport/lib/http/request.js:48:29)
    at /Users/alexander/Sites/TCP-Express/routes/auth.js:81:9
    at allFailed (/Users/alexander/Sites/TCP-Express/node_modules/passport/lib/middleware/authenticate.js:87:18)
    at attempt (/Users/alexander/Sites/TCP-Express/node_modules/passport/lib/middleware/authenticate.js:160:28)
    at Strategy.strategy.fail (/Users/alexander/Sites/TCP-Express/node_modules/passport/lib/middleware/authenticate.js:277:9)
    at verified (/Users/alexander/Sites/TCP-Express/node_modules/passport-local/lib/strategy.js:82:30)
    at Query.<anonymous> (/Users/alexander/Sites/TCP-Express/passport.js:58:11)
    at /Users/alexander/Sites/TCP-Express/node_modules/mongoose/node_modules/kareem/index.js:177:19
    at /Users/alexander/Sites/TCP-Express/node_modules/mongoose/node_modules/kareem/index.js:109:16
    at nextTickCallbackWith0Args (node.js:452:9)
    at process._tickCallback (node.js:381:13)
```

If I put that `{session: false}` part in there shouldn't it stop throwing this error?

**Comment by Arcrammer** [comment]
Okay nevermind I think I just needed to use the `return` keyword. After making them `return res.json()` they work again. It's been a long time since I used Express! haha.

**Comment by LeTranAnhVu** [comment]
> Ran into the same issue. When running passport.authenticate, add in an option saying you don't want a session. Like this:
> 
> ```
> app.post('/auth/facebook/token', passport.authenticate('facebook-token', {
>     session: false
>   })
> );
> ```

It took me 4 hours, when it always returns 401. Thank you a lot
