### ISSUE TITLE
How to catch wrong access_token error ?

### ISSUE THREAD

**Issue by MocanuMarius** [drudge/passport-facebook-token#72]
Hi , i inserted a malformed access_token purposefully and i'm getting this error in the console along with a "500" internal server error response. I want it to be 401 not 500, how to configureto catch the error, since the first param is accessToken and not "err" ?

```
:35 9fb3fbda359f Error
2017-04-23 13:09:35 9fb3fbda359f     at /data/app/node_modules/passport-facebook-token/lib/index.js:155:32
2017-04-23 13:09:35 9fb3fbda359f     at passBackControl (/data/app/node_modules/oauth/lib/oauth2.js:132:9)
2017-04-23 13:09:35 9fb3fbda359f     at IncomingMessage.<anonymous> (/data/app/node_modules/oauth/lib/oauth2.js:157:7)
2017-04-23 13:09:35 9fb3fbda359f     at emitNone (events.js:91:20)
2017-04-23 13:09:35 9fb3fbda359f     at IncomingMessage.emit (events.js:188:7)
2017-04-23 13:09:35 9fb3fbda359f     at endReadableNT (_stream_readable.js:975:12)
2017-04-23 13:09:35 9fb3fbda359f     at _combinedTickCallback (internal/process/next_tick.js:80:11)
2017-04-23 13:09:35 9fb3fbda359f     at process._tickCallback (internal/process/next_tick.js:104:9)


```

**Comment by akapei** [comment]
Add a callback to handle the error. See @mkemalsan answer here:
 [https://github.com/jaredhanson/passport-facebook/issues/93](url)

My version:
```javascript
router.get('/auth', passport.authenticate('facebook-token'),
    (req, res) => {
        if(req.user.err){
            res.status(401).json({
                success: false,
                message: 'Auth failed',
                error: req.user.err
            })
        }
        else if(req.user) {
            const user = {user_id: req.user.id}
            const token = jwt.sign(user, '##########', {
                expiresIn: "30d"
            })
            res.status(200).json({
                success: true,
                message: 'Enjoy your token!',
                token: token,
                user: req.user
            })
        } else {
            res.status(401).json({
                success: false,
                message: 'Auth failed'
            })
        }
    },
    // add this callback for handling errors. Then you can set responses with codes or 
    // redirects as you like.
    (error, req, res, next) => {
        if(error) {
            res.status(400).json({success: false, message: 'Auth failed', error})
        }
    }
)
```
