### ISSUE TITLE
Error: connect ETIMEDOUT 93.46.8.89:443

### ISSUE THREAD

**Issue by MarkAntonio** [drudge/passport-facebook-token#75]
Hello,

Would like to seek your assistance. I have spent a day searching for resources on how to go about this but could not solve this. I am encountering this issue only when running behind a proxy...
Error: connect ETIMEDOUT 93.46.8.89:443
    at /node_modules/passport-facebook-token/lib/index.js:155:32
    at ClientRequest.<anonymous> (/node_modules/oauth/lib/oauth2.js:162:5)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at emitErrorNT (net.js:1277:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)

Please advise.
Thanks.

**Comment by MarkAntonio** [comment]
Have solved this by using global-tunnel-ng. Thanks.
