### ISSUE TITLE
Error is thrown on calling the route

### ISSUE THREAD

**Issue by maheshambiga** [drudge/passport-facebook-token#82]
Getting below exception when passport route is hit,

Error
    at /Users/mambig/Downloads/angular2-node-fb-login-master/backend/node_modules/passport-facebook-token/lib/index.js:155:32
    at passBackControl (/Users/mambig/Downloads/angular2-node-fb-login-master/backend/node_modules/oauth/lib/oauth2.js:132:9)
    at IncomingMessage.<anonymous> (/Users/mambig/Downloads/angular2-node-fb-login-master/backend/node_modules/oauth/lib/oauth2.js:157:7)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:188:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

Express route config,
`router.route('/auth/facebook').post(passport.authenticate('facebook-token', {session: false}), function(req, res, next) {
   
    if (!req.user) {
      return res.send(401, 'User Not Authenticated');
    }

    // prepare token for API
    req.auth = {
      id: req.user.id
    };

    next(); 
}, generateToken, sendToken);`

**Comment by tomwagner** [comment]
You can use Express default error handler option (form Express doc: [http://expressjs.com/en/guide/error-handling.html#the-default-error-handler](http://expressjs.com/en/guide/error-handling.html#the-default-error-handler) ). And handle Oauth error something like this. 

```
import { InternalOAuthError } from 'passport-oauth';
...
routes ...
...
app.use((err, req, res, next) => {
  if (err instanceof InternalOAuthError) {
    res.status(401).send({
      error: true,
      data: err.message
    });
  }
  next(err);
});

```
